import { Moment } from 'moment';
import * as moment from 'moment';

export class UploadExcel {
  vendorCode?: string;
  vendorSKU?: string;
  barcode?: string;
  barcodeType?: string;
  productName?: string;
  itemName?: string;
  brandName?: string;
  productCategory?: string;
  productSubCategory?: string;
  productAttribute?: string;
  productOption?: string;
  releaseDate?: Moment;
  availableDate?: Moment;
  productType?: string;
  longDescription?: string;
  shortDescription?: string;
  modelName?: string;
  modelNumber?: string;
  noOfPieces?: number;
  noOfItem?: number;
  productMaterial?: string;
  whatInTheBox?: string;
  manufacture?: string;
  videoUrl?: string;
  careInstruction?: string;
  specialFeatures?: string;
  quantityOnHand?: number;
  highlights?: string;
  searchKeywords?: string;
  productComplianceCertificate?: string;
  genuineAndLegal?: boolean;
  countryOfOrigin?: string;
  instructionsForUsageAndSideEffects?: string;
  safetyWarnning?: string;
  warrentyPeriod?: string;
  warrantyType?: string;
  dangerousGoodsRegulations?: string;
  sellingPrice?: number;
  retailPrice?: number;
  currencyCode?: string;
  itemLength?: number;
  itemLengthUnit?: string;
  itemWidth?: number;
  itemWidthUnit?: string;
  itemHeight?: number;
  itemHeightUnit?: string;
  itemWeight?: number;
  itemWeightUnit?: string;
  itemPackageLength?: number;
  packageLengthUnit?: string;
  itemPackageWidth?: number;
  packageWidthUnit?: string;
  itemPackageHeight?: number;
  packageHeightUnit?: string;
  itemPackageWeight?: number;
  itemPackageWeightUnit?: string;
  remark?: boolean;

  constructor(data) {
    {
      this.vendorCode = data['Vendor Code'] || '';
      this.vendorSKU = data['Vendor SKU'] || '';
      this.barcode = data.Barcode || '';
      this.barcodeType = data['Barcode Type'] || '';
      this.itemName = data['Item Name'] || '';
      this.productName = data['Item Name'].split('-')[0].trim();
      this.brandName = data['Brand Name'] || '';
      this.productCategory = data['Product Cateogory'] || '';
      this.productSubCategory = data['Product Sub Category'] || '';
      this.productAttribute = data['Product Attribute'] || '';
      this.productOption = data['Product Option'] || '';
      this.releaseDate = moment(data['Release Date'], 'YYYY-MM-DD') || moment();
      this.availableDate = moment(data['Available Date'], 'YYYY-MM-DD') || moment();
      this.longDescription = data['Long Descriptions'] || '';
      this.shortDescription = data['Short Descriptions'] || '';
      this.modelName = data['Model Name'] || '';
      this.modelNumber = data['Model Number'] || '';
      this.noOfPieces = data['Number Of Pieces'] || 0;
      this.noOfItem = data['Number Of Item'] || 0;
      this.productMaterial = data['Product Material'] || '';
      this.whatInTheBox = data['What In the box'] || '';
      this.manufacture = data.Manufacture || '';
      this.videoUrl = data['Video Url'] || '';
      this.careInstruction = data['Care Instruction'] || '';
      this.specialFeatures = data['Special Features'] || '';
      this.quantityOnHand = data['Quantity On Hand'];
      this.highlights = data.Highlights || '';
      this.searchKeywords = data['Search Keywords'] || '';
      this.productComplianceCertificate = data['Product Compliance Certificate'] || '';
      this.genuineAndLegal = data['Genuine And Legal'].toLowerCase() === 'yes' ? true : false || false;
      this.countryOfOrigin = data['Country Of Origin'] || '';
      this.instructionsForUsageAndSideEffects = data['Instructions For Usage And Side Effects'] || '';
      this.safetyWarnning = data['Safety Warnning'] || '';
      this.warrentyPeriod = data['Warrenty Period'] || '';
      this.warrantyType = data['Warrenty Type'] || '';
      this.dangerousGoodsRegulations = data['Dangerous Goods Regulations'] || '';
      this.sellingPrice = data['Selling Price'] || 0.0;
      this.retailPrice = data['Retail Price'] || 0.0;
      this.currencyCode = data['Currency Code'] || '';
      this.itemLength = data['Item Length'] || 0;
      this.itemLengthUnit = data['Item Length Unit'] || '';
      this.itemWidth = data['Item Width'] || 0;
      this.itemWidthUnit = data['Item Width Unit'] || '';
      this.itemHeight = data['Item Height'] || 0;
      this.itemHeightUnit = data['Item Height Unit'] || '';
      this.itemWeight = data['Item Weight'] || 0;
      this.itemWeightUnit = data['Item Weight Unit'] || '';
      this.itemPackageLength = data['Item Package Length'] || 0;
      this.packageLengthUnit = data['Package Length Unit'] || '';
      this.itemPackageWidth = data['Item Package Width'] || 0;
      this.packageWidthUnit = data['Package Width Unit'] || '';
      this.itemPackageHeight = data['Item Package Height'] || 0;
      this.packageHeightUnit = data['Package Height Unit'] || '';
      this.itemPackageWeight = data['Item Package Weight'] || 0;
      this.itemPackageWeightUnit = data['Item Package Weight Unit'];
      this.remark = data.Remark || '';
    }
  }
}
